### ISSUE TITLE
Why not use the official YouTube RSS feeds?

### ISSUE THREAD

**Issue by peter279k** [dmackca/youtube-v3-rss#2]
As title. According to this Blog [post](https://danielmiessler.com/blog/rss-feed-youtube-channel/#gs.q5T03Eg), it shows how to make the RSS feeds for the specified channel.

Here is the video RSS feed example:

```
https://www.youtube.com/feeds/videos.xml?channel_id=UCBcRF18a7Qf58cCRy5xuWwQ
```

I think it can be more convenient than generating the RSS feed manually.
The ```php-youtube-api``` only searches the channel id.

**Comment by dmackca** [comment]
Youtube didn't expose any kind of public RSS feed at the time this repo was made! It does now, but I think it's still _only for user uploads_. A user's uploads are technically a "playlist," and this app lets you make a feed for any public playlist (including user's favorites, if they're public). Also, this app produces feeds with nicer formatting, thumbnails, and details. 

Newsblur has this same functionality built in now, so you can add a user or a playlist URL as if it were a feed, so this app isn't as crucial as it once was... but maybe it still provides value to people outside of Newsblur.
