### ISSUE TITLE
The app at herokuapp is not working

### ISSUE THREAD

**Issue by turbodude** [dmackca/youtube-v3-rss#4]
Hello! 
sorry if this is a wrong place to report this but morning-retreat-1911.herokuapp.com hasn't been working since a couple of days ago

**Comment by dmackca** [comment]
I bet that's because I ran out of monthly free dyno credits on Heroku. I think it'll stop working on the 22nd of the month and then start up again on the 1st. If lots of people are using the demo, maybe I'll move it to a different host... some day.

**Comment by turbodude** [comment]
OK, thanks for the clarification.

**Comment by dmackca** [comment]
The demo app is shutting down this week, so unfortunately this issue is a "wontfix" 😭

**Comment by codeshark1** [comment]
So the whole thing won't work? Do you know of any alternatives?

**Comment by dmackca** [comment]
You can fork this repo and spin up a version for your own use, but I'm going to change the project homepage to recommend [NewsBlur](https://newsblur.com/), which lets you subscribe to YouTube channels as RSS feeds. It's what I've been using for the past several years anyway. If there's a type of playlist that isn't supported in NewsBlur, the developer is always open to suggestions (and pull requests!)

If you *do* fork this repo and make a version that's compliant with their terms, I'd definitely take a look at a pull request too :P

I'm glad people appreciate this app and find it useful! Too bad Google is such a hassle 😅 

edit: I updated the demo app's homepage with some info: https://morning-retreat-1911.herokuapp.com/
